ajax/ajaxapp/urls.py
from django.urls import path
from .views import item_form


urlpatterns = [
    path('', item_form, name='item_form'),
]

ajax/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ajaxapp.urls'))
]

ajax/ajaxapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

class Item(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

ajax/ajaxapp/forms.py
from django import forms
from .models import Category, Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category', 'name']

ajax/ajaxapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Category, Item
from .forms import ItemForm


def item_form(request):
    form = ItemForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()

    return render(request, 'index.html', {'form': form})


def get_items_by_category(request):
    category_id = request.GET.get('category_id')
    items = Item.objects.filter(category_id=category_id)
    item_list = [{'id': item.id, 'name': item.name} for item in items]
    return JsonResponse({'items': item_list})

ajax/ajaxapp/templates/index.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Сохранить</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('#id_category').change(function() {
      var category_id = $(this).val();
      $.ajax({
        url: '/get_items_by_category/',
        data: {'category_id': category_id},
        dataType: 'json',
        success: function(data) {
          var items = data.items;
          var itemSelect = $('#id_name');
          itemSelect.empty();
          for (var i = 0; i < items.length; i++) {
            itemSelect.append('<option value="' + items[i].id + '">' + items[i].name + '</option>');
          }
        }
      });
    });
  });
</script>